### ISSUE TITLE
Not working in my system Ubuntu 24.10

### ISSUE THREAD

**Issue by Umang-Chaurasia** [maniacx/Battery-Health-Charging#120]
After updating and restart this extention has no response before it was working fine.

**Comment by maniacx** [comment]
Ubuntu and Debian based system have an issue with polkit 124, 125.

For some reason it is taking around 2 - 3 minutes to execute pkexec command through gnome-shell.

But this happens only in wayland.

Unfortunately I haven't found a fix yet.
It is not related to extension, but something to do with ubuntu/debian based system running wayland.

It works on fedora wayland and other distro.

**Comment by maniacx** [comment]
Where did you update extension from? Github?

**Comment by Umang-Chaurasia** [comment]
ubuntu with wayland 24.10, extension already upto date and working fine  before i update it to 24.10. It takes 2 3 minutes to start the extension i think it was ubuntu creating problem. Afterwards it starts and extension is unable to switch modes stuck at balanced mode neither shifting in full capacity nor in maximum life span. As i try to do that it automatically closes the dropdown menu and no notification received of changing mode.

**Comment by maniacx** [comment]
Just to test, can you try using Xorg.

Log out and click on your login name. 

Before you enter the password.
There will be a small geared shaped button on bottom right corner, you can switch between **Ubuntu** (which is wayland) and **Ubuntu with Xorg**

**Comment by maniacx** [comment]
Deleted

**Comment by seffs** [comment]
Hi. I have the same problem.

I can confirm this happens only on Wayland. It works fine on X11.

> Ubuntu and Debian based system have an issue with polkit 124, 125. 

Do you have any related links? Might be worth reporting upstream

EDIT: Also running Ubuntu 24.10. I tried integrated, hybrid and nvidia mode, but it made no difference.

**Comment by maniacx** [comment]
Yes. I asked in the gnome-extension matrix group channel. Nobody could help me with this.

Ubuntu forum. No reply yet

https://ubuntuforums.org/showthread.php?t=2502156

Polkit. (There was a misleading information ab from my ended up closing of the issue) 

You can read below.

https://github.com/polkit-org/polkit/issues/510


Problem is
1. This issue of delayed execution when using pkexec is only in debian trixie (polkit 125) and ubuntu 24.10 (polkit124) based system running wayland. In X11 it works on both system works fine, no delays.

2. In Fedora 40 (polkit 124) and Fedora 41 (polkit 125) there is no delay in Wayland/X11

I am not sure how to debug this.
From what little knowledge I have i have checked the pam configuration,  disabled app Armour, added user as wheel, nothing helped so far. Logs also do not show anything.

I have been delaying my new release for more than a month , in hope I would find the bug.😒

**Comment by maniacx** [comment]
@seffs 
@Umang-Chaurasia 

I have created a script to use `sudo`  to be used as a workaround as I cannot solve the bugs with `polkit`. We can continue, our testing and discussion on this thread.

https://github.com/maniacx/Battery-Health-Charging/issues/122

I will close this issue.
