### ISSUE TITLE
Unify selected item with Energy Mode

### ISSUE THREAD

**Issue by ai** [maniacx/Battery-Health-Charging#26]
GNOME settings dropdown already have a similar list with modes, Energy More. But it uses `✓` mark instead of `•` to highlight the current element.

Should we use the same marker?

![Captura desde 2023-04-25 00-48-31](https://user-images.githubusercontent.com/19343/234132662-005843d2-fc7e-4ef6-a64c-f0506dc5a303.png)

![Captura desde 2023-04-25 00-48-00](https://user-images.githubusercontent.com/19343/234132600-6b5549aa-1bf5-4c43-bdb3-f45e2ec663d7.png)

**Comment by maniacx** [comment]
I changed my extension to checkmark. However I don't know if it looks the same as in **power mode**.
I have on two modes of powerprofile so no popupmenu.
Could you install this **test** version and verify it looks the same as in power profile.
[test.zip](https://github.com/maniacx/Battery-Health-Charging/files/11315526/test.zip)

If during install you get **msgfmt** error. install gettext
sudo apt install gettext
or
sudo dnf install gettext


That check mark looks ugly and little out of place though. 
But for consistency I will include it in my next update, if you confirm it looks the same as your **power mode**.

![Screenshot from 2023-04-24 20-48-34](https://user-images.githubusercontent.com/4295343/234149252-cef73474-faee-4772-abae-33903a0b2ce8.png)

I wish they would make it look more like the wifi check mark.
![Screenshot from 2023-04-24 20-48-09](https://user-images.githubusercontent.com/4295343/234149322-c2b90044-2d87-4578-a32b-bd1ebadf05cf.png)





Let me know if look the same, i will include it

**Comment by maniacx** [comment]
Yes. Hope so gnome does implement something to fix this.

 I have already released a version 14 on gnome extension with ornament changed from DOT to CHECK. I will close the issue.
Thanks for reporting.
