### ISSUE TITLE
Port to GNOME 45

### ISSUE THREAD

**Issue by AbrarSL** [maniacx/Battery-Health-Charging#56]
I thought it'd be a good idea to put a little reminder here. GNOME 45 may not be out yet however starting the port early might be a good idea because of the drastic changes needed.

https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by maniacx** [comment]
My laptop screen broke. So until I repair or can afford to by a new laptop there might be no more updates. :( 
Screen itself is 300 USD

**Comment by yochananmarqos** [comment]
@maniacx Just tested on GNOME 45.rc and it's working fine. Thanks!

**Comment by AbrarSL** [comment]
It seems to work great. I'll close the issue.
