### ISSUE TITLE
not compatible with advan workplus

### ISSUE THREAD

**Issue by orangpelupa** [maniacx/Battery-Health-Charging#66]
hi, it says its not commpatible with advan workplus. 

dunno this helps  or not

ls -l /sys/class/power_supply
result in this

`total 0
lrwxrwxrwx 1 root root 0 Okt 11  2023 ADP1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ADP1
lrwxrwxrwx 1 root root 0 Okt 11  2023 BAT0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0
`

**Comment by maniacx** [comment]
Tried to get some information about advan workplus and it seems like doesn't support chaning charging threshold / limit.
(I may be wrong though)

Fo this extension to work
* First laptop's  hardware (EC) should support charging threshold .
* Secondly, changing threshold should be support by a linux via kernel wmi or some packages using command-line


If it is possible to change charging threshold  on your  laptop  using command-line , let me know.
