### ISSUE TITLE
Compatibility with Microsoft Surface devices

### ISSUE THREAD

**Issue by vistis** [maniacx/Battery-Health-Charging#73]
As the title suggests.

I know that Microsoft Surface devices aren't super popular within the Linux circle, so there probably isn't a big incentive to support them. Plus, it would probably be pretty hard to achieve, too.

For your consideration.
Thanks

**Comment by maniacx** [comment]
Hello @vistis 
Usually this feature shoud be supported by linux kernel  (or via some executables) to set charging threshold for device via command line in Linux.
 
I found below link for linux development patches for surface, but could not find any info on regarding charging threshold.
May be you can request to support the feature on the repo below.
https://github.com/linux-surface/linux-surface

**Comment by maniacx** [comment]
Also ping me back here, when is linux-surface kernel supports Charging threshold. I will add it to this extension
