### ISSUE TITLE
Battery status icon always as charging.

### ISSUE THREAD

**Issue by danroxha** [maniacx/Battery-Health-Charging#90]
## Laptop:
 - Model: Legion Slim 5 16IRH
 - OS: Fedora Linux 40 (Workstation Edition) x86_64
 - DE: GNOME 46.1
 
 ## Problem
The extension does not change the icon to symbolize the end of battery power given the conservative limit enabled.

- Extension enabled 
![image](https://github.com/maniacx/Battery-Health-Charging/assets/38236602/8477cec5-8d6c-48dc-8ec1-bee0105395e3)

- Extension disabled
![image](https://github.com/maniacx/Battery-Health-Charging/assets/38236602/111c9bf3-5e92-41b0-970e-f91eb09718ba)

 Conservation mode  enabled
 ```sh
 cat '/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode'
1
```
## More:
```sh
~: cat /sys/class/power_supply/BAT1/status
Not charging
~: cat /sys/class/power_supply/BAT1/capacity
79

```

**Comment by maniacx** [comment]
Sorry. I didnt understand your post. (May be translation)

Are you talking about system charging power icons as shown in the picture below?
![Screenshot from 2024-05-07 08-34-48](https://github.com/maniacx/Battery-Health-Charging/assets/4295343/7ee428ce-6e0d-4653-a350-0c6ebbb93b6f)

Is the charger plugged in and powered up?
Or is it charger disconnected from the laptop?


Also try to enable or disable this settings.
![Screenshot from 2024-05-07 08-41-07](https://github.com/maniacx/Battery-Health-Charging/assets/4295343/e7cb08a1-6678-47fb-b5c2-88d84a221d72)

**Comment by MaximalCats** [comment]
Have you found a fix? It's purely cosmetical (battery is in fact, not charging), but still annoying.

**Comment by maniacx** [comment]
@MaximalCats 

In extension prefs, **Change Battery indication icon behavior** enable it.
Let me, me know if it doesnot work for you.

**Comment by MaximalCats** [comment]
> @MaximalCats
> 
> In extension prefs, **Change Battery indication icon behavior** enable it. Let me, me know if it doesnot work for you.

Did not work, but now I'm thinking the entire extension doesn't work (battery level stays at 99%)

**Comment by maniacx** [comment]
@MaximalCats
Lets discuss this here
https://github.com/maniacx/Battery-Health-Charging/issues/105
